trigger:
- main

pool:
  vmImage: ubuntu-latest

steps:

# ✅ Java + Maven setup for backend
- task: Maven@3
  inputs:
    mavenPomFile: 'backend/pom.xml'
    goals: 'clean test'
    javaHomeOption: 'JDKVersion'
    jdkVersionOption: '1.17'
    mavenVersionOption: 'Default'
    publishJUnitResults: true
    testResultsFiles: '**/surefire-reports/TEST-*.xml'
  displayName: 'Run Backend Unit Tests'
